spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/25_06_Spring?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 
  mvc:
    view:
      prefix: /WebInfo
      suffix: .jsp
mybatis:
  type-aliases-package: com.KoreaIT.shw.vo
  mapper-locations: classpath:/mappers/**/*.xml